package prc03;
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
//
//                    Source Code Generated by
//                           CA Gen 8.6
//
//    Copyright (c) 2020 CA Technologies. All rights reserved.
//
//    Name: B25EX709_IA                      Date: 2020/03/11
//    User: YWH0NKF                          Time: 16:48:32
//
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// Import Statements
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
import java.lang.*;
import java.io.*;
import java.util.*;
import java.math.*;
import java.sql.*;
import com.ca.gen.vwrt.*;
import com.ca.gen.vwrt.types.*;
import com.ca.gen.vwrt.vdf.*;
import com.ca.gen.csu.exception.*;

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// START OF IMPORT VIEW
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
/**
 * Internal data view storage for: B25EX709_IA
 **/
public class B25EX709_IA extends ViewBase implements IImportView, Serializable
{
  // Entity View: IMP_FILTER
  //        Type: EWW_SUPPLIED
  /**
   * Attribute missing flag for: ImpFilterEwwSuppliedEvaluationDate
   **/
  public char ImpFilterEwwSuppliedEvaluationDate_AS;
  /**
   * Attribute for: ImpFilterEwwSuppliedEvaluationDate
   * Domain: Date
   * Length: 8
   **/
  public int ImpFilterEwwSuppliedEvaluationDate;
  /**
   * Default Constructor
   **/
  
  public B25EX709_IA()
  {
    reset();
  }
  /**
   * Copy Constructor
   **/
  
  public B25EX709_IA(B25EX709_IA orig)
  {
    copyFrom(orig);
  }
  /**
   * Static instance creator function
   **/
  
  public static B25EX709_IA getInstance()
  {
    return new B25EX709_IA();
  }
  /**
   * Static free instance method
   **/
  
  public void freeInstance()
  {
  }
  /**
   * clone constructor
   **/
  
  @Override public Object clone()
  	throws CloneNotSupportedException
  {
    return(new B25EX709_IA(this));
  }
  /**
   * Resets all properties to the defaults.
   **/
  
  public void reset()
  {
    ImpFilterEwwSuppliedEvaluationDate_AS = ' ';
    ImpFilterEwwSuppliedEvaluationDate = 00000000;
  }
  /**
   * Gets the VDF version of the current state of the instance.
   **/
  public VDF getVDF()
  {
    throw new RuntimeException("can only execute getVDF for a Procedure Step.");
  }
  
  /**
   * Sets the current state of the instance to the VDF version.
   **/
  public void setFromVDF(VDF vdf)
  {
    throw new RuntimeException("can only execute setFromVDF for a Procedure Step.");
  }
  
  /**
   * Sets the current instance based on the passed view.
   **/
  public void copyFrom(IImportView orig)
  {
    this.copyFrom((B25EX709_IA) orig);
  }
  
  /**
   * Sets the current instance based on the passed view.
   **/
  public void copyFrom(B25EX709_IA orig)
  {
    ImpFilterEwwSuppliedEvaluationDate_AS = orig.ImpFilterEwwSuppliedEvaluationDate_AS;
    ImpFilterEwwSuppliedEvaluationDate = orig.ImpFilterEwwSuppliedEvaluationDate;
  }
}
