package gct;
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
//
//                    Source Code Generated by
//                           CA Gen 8.6
//
//    Copyright (c) 2020 CA Technologies. All rights reserved.
//
//    Name: B04EX105_OA                      Date: 2020/04/23
//    User: 798155                           Time: 17:09:49
//
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// Import Statements
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
import java.lang.*;
import java.io.*;
import java.util.*;
import java.math.*;
import java.sql.*;
import com.ca.gen.vwrt.*;
import com.ca.gen.vwrt.types.*;
import com.ca.gen.vwrt.vdf.*;
import com.ca.gen.csu.exception.*;

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// START OF EXPORT VIEW
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
/**
 * Internal data view storage for: B04EX105_OA
 **/
public class B04EX105_OA extends ViewBase implements IExportView, Serializable
{
  // Entity View: EXP
  //        Type: IGC1_DA_CODE_TABLES
  /**
   * Attribute for: ExpIgc1DaCodeTablesRecordsAdded
   * Domain: Number
   * Length: 15
   * Decimal Places: 0
   * Decimal Precision: N
   **/
  public double ExpIgc1DaCodeTablesRecordsAdded;
  /**
   * Attribute for: ExpIgc1DaCodeTablesRecordsDeleted
   * Domain: Number
   * Length: 15
   * Decimal Places: 0
   * Decimal Precision: N
   **/
  public double ExpIgc1DaCodeTablesRecordsDeleted;
  /**
   * Attribute for: ExpIgc1DaCodeTablesValuesProcessed
   * Domain: Number
   * Length: 15
   * Decimal Places: 0
   * Decimal Precision: N
   **/
  public double ExpIgc1DaCodeTablesValuesProcessed;
  // Entity View: EXP
  //        Type: EWW_COMPONENT
  /**
   * Attribute for: ExpEwwComponentReturnCode
   * Domain: Number
   * Length: 5
   * Decimal Places: 0
   * Decimal Precision: N
   **/
  public int ExpEwwComponentReturnCode;
  /**
   * Attribute for: ExpEwwComponentReasonCode
   * Domain: Number
   * Length: 5
   * Decimal Places: 0
   * Decimal Precision: N
   **/
  public int ExpEwwComponentReasonCode;
  /**
   * Attribute for: ExpEwwComponentOriginServid
   * Domain: Number
   * Length: 15
   * Decimal Places: 0
   * Decimal Precision: N
   **/
  public double ExpEwwComponentOriginServid;
  /**
   * Attribute for: ExpEwwComponentRollbackIndicator
   * Domain: Text
   * Length: 1
   * Varying Length: N
   **/
  public String ExpEwwComponentRollbackIndicator;
  /**
   * Attribute for: ExpEwwComponentSeverityCode
   * Domain: Text
   * Length: 1
   * Varying Length: N
   **/
  public String ExpEwwComponentSeverityCode;
  /**
   * Default Constructor
   **/
  
  public B04EX105_OA()
  {
    reset();
  }
  /**
   * Copy Constructor
   **/
  
  public B04EX105_OA(B04EX105_OA orig)
  {
    copyFrom(orig);
  }
  /**
   * Static instance creator function
   **/
  
  public static B04EX105_OA getInstance()
  {
    return new B04EX105_OA();
  }
  /**
   * Static free instance method
   **/
  
  public void freeInstance()
  {
  }
  /**
   * clone constructor
   **/
  
  @Override public Object clone()
  	throws CloneNotSupportedException
  {
    return(new B04EX105_OA(this));
  }
  /**
   * Resets all properties to the defaults.
   **/
  
  public void reset()
  {
    ExpIgc1DaCodeTablesRecordsAdded = 0.0;
    ExpIgc1DaCodeTablesRecordsDeleted = 0.0;
    ExpIgc1DaCodeTablesValuesProcessed = 0.0;
    ExpEwwComponentReturnCode = 0;
    ExpEwwComponentReasonCode = 0;
    ExpEwwComponentOriginServid = 0.0;
    ExpEwwComponentRollbackIndicator = " ";
    ExpEwwComponentSeverityCode = " ";
  }
  /**
   * Sets the current state of the instance to the VDF version.
   **/
  public void setFromVDF(VDF vdf)
  {
    throw new RuntimeException("can only execute setFromVDF for a Procedure Step.");
  }
  
  /**
   * Gets the VDF version of the current state of the instance.
   **/
  public VDF getVDF()
  {
    throw new RuntimeException("can only execute getVDF for a Procedure Step.");
  }
  
  /**
   * Sets the current instance based on the passed view.
   **/
  public void copyFrom(IExportView orig)
  {
    this.copyFrom((B04EX105_OA) orig);
  }
  
  /**
   * Sets the current instance based on the passed view.
   **/
  public void copyFrom(B04EX105_OA orig)
  {
    ExpIgc1DaCodeTablesRecordsAdded = orig.ExpIgc1DaCodeTablesRecordsAdded;
    ExpIgc1DaCodeTablesRecordsDeleted = orig.ExpIgc1DaCodeTablesRecordsDeleted;
    ExpIgc1DaCodeTablesValuesProcessed = orig.ExpIgc1DaCodeTablesValuesProcessed;
    ExpEwwComponentReturnCode = orig.ExpEwwComponentReturnCode;
    ExpEwwComponentReasonCode = orig.ExpEwwComponentReasonCode;
    ExpEwwComponentOriginServid = orig.ExpEwwComponentOriginServid;
    ExpEwwComponentRollbackIndicator = orig.ExpEwwComponentRollbackIndicator;
    ExpEwwComponentSeverityCode = orig.ExpEwwComponentSeverityCode;
  }
}
