package gct;
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
//
//                    Source Code Generated by
//                           CA Gen 8.6
//
//    Copyright (c) 2020 CA Technologies. All rights reserved.
//
//    Name: B04EX105_IA                      Date: 2020/04/23
//    User: 798155                           Time: 17:09:49
//
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// Import Statements
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
import java.lang.*;
import java.io.*;
import java.util.*;
import java.math.*;
import java.sql.*;
import com.ca.gen.vwrt.*;
import com.ca.gen.vwrt.types.*;
import com.ca.gen.vwrt.vdf.*;
import com.ca.gen.csu.exception.*;

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// START OF IMPORT VIEW
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
/**
 * Internal data view storage for: B04EX105_IA
 **/
public class B04EX105_IA extends ViewBase implements IImportView, Serializable
{
  // Entity View: IMP
  //        Type: IGC1_CODE_TABLE
  /**
   * Attribute for: ImpIgc1CodeTableCodeTableCode
   * Domain: Text
   * Length: 6
   * Varying Length: N
   **/
  public String ImpIgc1CodeTableCodeTableCode;
  // Entity View: IMP_DISPLAY_MSGS_FLAG
  //        Type: IEF_SUPPLIED
  /**
   * Attribute for: ImpDisplayMsgsFlagIefSuppliedFlag
   * Domain: Text
   * Length: 1
   * Varying Length: N
   **/
  public String ImpDisplayMsgsFlagIefSuppliedFlag;
  /**
   * Default Constructor
   **/
  
  public B04EX105_IA()
  {
    reset();
  }
  /**
   * Copy Constructor
   **/
  
  public B04EX105_IA(B04EX105_IA orig)
  {
    copyFrom(orig);
  }
  /**
   * Static instance creator function
   **/
  
  public static B04EX105_IA getInstance()
  {
    return new B04EX105_IA();
  }
  /**
   * Static free instance method
   **/
  
  public void freeInstance()
  {
  }
  /**
   * clone constructor
   **/
  
  @Override public Object clone()
  	throws CloneNotSupportedException
  {
    return(new B04EX105_IA(this));
  }
  /**
   * Resets all properties to the defaults.
   **/
  
  public void reset()
  {
    ImpIgc1CodeTableCodeTableCode = "      ";
    ImpDisplayMsgsFlagIefSuppliedFlag = " ";
  }
  /**
   * Gets the VDF version of the current state of the instance.
   **/
  public VDF getVDF()
  {
    throw new RuntimeException("can only execute getVDF for a Procedure Step.");
  }
  
  /**
   * Sets the current state of the instance to the VDF version.
   **/
  public void setFromVDF(VDF vdf)
  {
    throw new RuntimeException("can only execute setFromVDF for a Procedure Step.");
  }
  
  /**
   * Sets the current instance based on the passed view.
   **/
  public void copyFrom(IImportView orig)
  {
    this.copyFrom((B04EX105_IA) orig);
  }
  
  /**
   * Sets the current instance based on the passed view.
   **/
  public void copyFrom(B04EX105_IA orig)
  {
    ImpIgc1CodeTableCodeTableCode = orig.ImpIgc1CodeTableCodeTableCode;
    ImpDisplayMsgsFlagIefSuppliedFlag = orig.ImpDisplayMsgsFlagIefSuppliedFlag;
  }
}
