package gct;

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
//
//                    Source Code Generated by
//                           CA Gen 8.6
//
//    Copyright (c) 2020 CA Technologies. All rights reserved.
//
//    Name: B04EX105_REFRESH_DA_CODE_TABLES  Date: 2020/04/23
//    Target OS:   JVM                       Time: 17:09:49
//    Target DBMS: JDBC                      User: 798155
//    Access Method: JDBC           
//
//    Generation options:
//    Debug trace option selected
//    Data modeling constraint enforcement not selected
//    Optimized import view initialization selected
//    Enforce default values with DBMS not selected
//    Init unspecified optional fields to NULL not selected
//
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// Import Statements
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
import java.lang.*;
import java.io.*;
import java.util.*;
import java.math.*;
import java.sql.*;
import com.ca.gen.vwrt.*;
import com.ca.gen.vwrt.types.*;
import com.ca.gen.vwrt.vdf.*;

import com.ca.gen.abrt.*;
import com.ca.gen.abrt.functions.*;
import com.ca.gen.abrt.cascade.*;
import com.ca.gen.abrt.trace.*;
import com.ca.gen.exits.common.*;
import com.ca.gen.odc.*;

public class B04EX105 extends ABBase {
	// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
	// IMPORT VIEW CLASS VARIABLE
	// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
	B04EX105_IA w_ia;
	// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
	// EXPORT VIEW CLASS VARIABLE
	// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
	B04EX105_OA w_oa;

	private int sqlcode;
	private int CntTblSeqNo;

	// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
	// MISC DECLARATIONS AND PROTOTYPES
	// FOLLOW AS NEEDED:
	// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
	// +-> B04EX105_REFRESH_DA_CODE_TABLES 04/23/2020 17:09
	// ! IMPORTS:
	// ! Entity View imp igc1_code_table (Transient, Mandatory,
	// ! Import only)
	// ! code_table_code
	// ! Work View imp_display_msgs_flag ief_supplied
	// ! (Transient, Optional, Import only)
	// ! flag
	// ! EXPORTS:
	// ! Entity View exp igc1_da_code_tables (Transient,
	// ! Export only)
	// ! records_added
	// ! records_deleted
	// ! values_processed
	// ! Work View exp eww_component (Transient, Export only)
	// ! return_code
	// ! reason_code
	// ! origin_servid
	// ! rollback_indicator
	// ! severity_code
	// !
	// ! EXTERNAL ACTION BLOCK
	// !
	// +---

	// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
	// CONSTRUCTOR FOR THE CLASS
	// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
	public B04EX105() {
		iefCGenRlse = "CA Gen 8.6";
		ssCopyright = "Copyright (c) 2020 CA Technologies. All rights reserved.";
		iefCGenDate = "2020/04/23";
		iefCGenTime = "17:09:49";
		iefCGenEncy = "9.2.A6";
		iefCGenUserId = "798155";
		iefCGenModel = "EWW GCT CODETABLES 01 02 D";
		iefCGenSubset = "ALL                             ";
		iefCGenName = "B04EX105_REFRESH_DA_CODE_TABLES";
		nestingLevel = 0;
		valChkDeadlockTimeout = false;
		valChkDBError = false;
	}
	// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
	// ACTION BLOCK FUNCTION DECLARATIONS
	// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

	public void B04EX105(Object in_runtime_parm1, IRuntimePStepContext in_runtime_parm2, GlobData in_globdata,
			B04EX105_IA import_view, B04EX105_OA export_view) {
		iefRuntimeParm1 = in_runtime_parm1;
		iefRuntimeParm2 = in_runtime_parm2;
		globdata = in_globdata;
		w_ia = import_view;
		w_oa = export_view;
		_B04EX105();
	}

	private void _B04EX105() {

		try {
			f_22020290();
		} catch (ABException e) {
		}
	}

	public void f_22020290() throws ABException {

		// User-written code should be inserted here

		sqlcode = 0;
		w_oa.ExpEwwComponentReturnCode = +1;
		w_oa.ExpEwwComponentReasonCode = +1;

	}
}// end class
