
spring:
  application:
    name: E2KModuleSample
  datasource:          url: 
            jdbc:h2:mem:testdb
            #file:"C:/data/sample"
            
          driverClassName: org.h2.Driver
          username: admin
          password: password
  jpa:    database-platform: org.hibernate.dialect.H2Dialect
  h2:    console:      enabled: true
      path: /h2
  
#server:
#    port: 9090